import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { GlobalChat } from "@/components/GlobalChat";
import { BottomNav } from "@/components/BottomNav";
import { getPenaColor } from "@/app/actions";
import { penaColorStyle } from "@/lib/pena-colors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = (await cookies()).get('auth')?.value === 'true';
  const penaColor = await getPenaColor();

  return (
    <html lang="es">
      <head>
        <style dangerouslySetInnerHTML={{ __html: penaColorStyle(penaColor) }} />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BottomNav isAdmin={isAdmin} />
        <div className="pb-20 md:pb-0">
          {children}
        </div>
        <GlobalChat />
      </body>
    </html>
  );
}
